<?php

use App\SuspectCase;
use Illuminate\Database\Seeder;

class SuspectCasesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        SuspectCase::CREATE(['sample_at'=>'04-03-2020','origin'=>'Hospital ETG','age'=>'48','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'10','epivigila'=> NULL,'pscr_sars_cov_2'=>'negative','paho_flu' => '105803','status' => 'Alta','observation' => 'DOCTORA ENVIA NOTIFICACION VIA MAIL','patient_id' =>'1']);
        SuspectCase::CREATE(['sample_at'=>'05-03-2020','origin'=>'Hospital ETG','age'=>'75','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'10','epivigila'=> NULL,'pscr_sars_cov_2'=>'negative','paho_flu' => '105802','status' => 'Alta','observation' => 'DOCTORA ENVIA NOTIFICACION VIA MAIL','patient_id' =>'2']);
        SuspectCase::CREATE(['sample_at'=>'05-03-2020','origin'=>'Hospital ETG','age'=>'33','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'10','epivigila'=> NULL,'pscr_sars_cov_2'=>'negative','paho_flu' => '105835','status' => 'Alta','observation' => 'DOCTORA ENVIA NOTIFICACION VIA MAIL','patient_id' =>'3']);
        SuspectCase::CREATE(['sample_at'=>'05-03-2020','origin'=>'Hospital ETG','age'=>'36','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'10','epivigila'=> NULL,'pscr_sars_cov_2'=>'negative','paho_flu' => '105808','status' => 'Alta','observation' => 'DOCTORA ENVIA NOTIFICACION VIA MAIL','patient_id' =>'4']);
        SuspectCase::CREATE(['sample_at'=>'06-03-2020','origin'=>'Hospital ETG','age'=>'50','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'10','epivigila'=> NULL,'pscr_sars_cov_2'=>'negative','paho_flu' => '105835','status' => 'Alta','observation' => 'DOCTORA ENVIA NOTIFICACION VIA MAIL','patient_id' =>'5']);
        SuspectCase::CREATE(['sample_at'=>'08-03-2020','origin'=>'Hospital ETG','age'=>'9','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'11','epivigila'=> NULL,'pscr_sars_cov_2'=>'negative','paho_flu' => '105850','status' => 'Alta','observation' => 'DOCTORA ENVIA NOTIFICACION VIA MAIL','patient_id' =>'6']);
        SuspectCase::CREATE(['sample_at'=>'10-03-2020','origin'=>'Hospital ETG','age'=>'57','gender'=>'female','result_ifd'=>'Influenza A','subtype' => 'H1N1','epidemiological_week'=>'11','epivigila'=>'50000','pscr_sars_cov_2'=>'negative','paho_flu' => '105868','status' => 'Alta','observation' => 'INFLUENZA A H1N1 ','patient_id' =>'7']);
        SuspectCase::CREATE(['sample_at'=>'10-03-2020','origin'=>'Hospital ETG','age'=>'57','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'11','epivigila'=>'50001','pscr_sars_cov_2'=>'negative','paho_flu' => '105867','status' => 'Alta','observation' => NULL,'patient_id' =>'8']);
        SuspectCase::CREATE(['sample_at'=>'10-03-2020','origin'=>'Hospital ETG','age'=>'16','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'11','epivigila'=>'50002','pscr_sars_cov_2'=>'negative','paho_flu' => '105866','status' => 'Alta','observation' => NULL,'patient_id' =>'9']);
        SuspectCase::CREATE(['sample_at'=>'11-03-2020','origin'=>'Hospital ETG','age'=>'62','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'11','epivigila'=>'50029','pscr_sars_cov_2'=>'negative','paho_flu' => '105877','status' => 'Alta','observation' => NULL,'patient_id' =>'10']);
        SuspectCase::CREATE(['sample_at'=>'12-03-2020','origin'=>'Hospital ETG','age'=>'60','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'11','epivigila'=> NULL,'pscr_sars_cov_2'=>'negative','paho_flu' => '105957','status' => 'Alta','observation' => NULL,'patient_id' =>'11']);
        SuspectCase::CREATE(['sample_at'=>'14-03-2020','origin'=>'Hospital ETG','age'=>'53','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=> NULL,'pscr_sars_cov_2'=>'negative','paho_flu' => '105920','status' => 'Alta','observation' => NULL,'patient_id' =>'12']);
        SuspectCase::CREATE(['sample_at'=>'15-03-2020','origin'=>'Hospital ETG','age'=>'38','gender'=>'female','result_ifd'=>'Influenza A','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'50666','pscr_sars_cov_2'=>'negative','paho_flu' => '105922','status' => 'Alta','observation' => NULL,'patient_id' =>'13']);
        SuspectCase::CREATE(['sample_at'=>'15-03-2020','origin'=>'Hospital ETG','age'=>'61','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'50885','pscr_sars_cov_2'=>'negative','paho_flu' => '105930','status' => 'Alta','observation' => NULL,'patient_id' =>'14']);
        SuspectCase::CREATE(['sample_at'=>'15-03-2020','origin'=>'Hospital ETG','age'=>'7','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'50668','pscr_sars_cov_2'=>'negative','paho_flu' => '105925','status' => 'Alta','observation' => NULL,'patient_id' =>'15']);
        SuspectCase::CREATE(['sample_at'=>'15-03-2020','origin'=>'Hospital ETG','age'=>'5','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'50669','pscr_sars_cov_2'=>'negative','paho_flu' => '105924','status' => 'Alta','observation' => NULL,'patient_id' =>'16']);
        SuspectCase::CREATE(['sample_at'=>'15-03-2020','origin'=>'Hospital ETG','age'=>'42','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'50667','pscr_sars_cov_2'=>'negative','paho_flu' => '105921','status' => 'Alta','observation' => NULL,'patient_id' =>'17']);
        SuspectCase::CREATE(['sample_at'=>'15-03-2020','origin'=>'Hospital ETG','age'=>'29','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'51640','pscr_sars_cov_2'=>'negative','paho_flu' => '105931','status' => 'Alta','observation' => NULL,'patient_id' =>'18']);
        SuspectCase::CREATE(['sample_at'=>'15-03-2020','origin'=>'Hospital ETG','age'=>'20','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=> NULL,'pscr_sars_cov_2'=>'negative','paho_flu' => '105929','status' => 'Alta','observation' => 'NO PUDO SER INGRESADO POR LA DOCTORA ENVIA MAIL A MARGARITA OSORIO INFORMANDO CASO','patient_id' =>'19']);
        SuspectCase::CREATE(['sample_at'=>'16-03-2020','origin'=>'Hospital ETG','age'=>'3','gender'=>'male','result_ifd'=>'Influenza A','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'50724','pscr_sars_cov_2'=>'negative','paho_flu' => '105927','status' => 'Alta','observation' => 'INFLUENZA A PENDIENTE TIPIFICACION 19/03/2020 ','patient_id' =>'20']);
        SuspectCase::CREATE(['sample_at'=>'16-03-2020','origin'=>'Hospital ETG','age'=>'40','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'50828','pscr_sars_cov_2'=>'negative','paho_flu' => '105928','status' => 'Alta','observation' => 'PACIENTE EXTRANJERA CON IDENTIFICACION LOCAL 19/03/2020 INFLUENZA A PENDIENTE TIPIFICACION 19/03/2020 ','patient_id' =>'21']);
        SuspectCase::CREATE(['sample_at'=>'16-03-2020','origin'=>'Hospital ETG','age'=>'34','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'50726','pscr_sars_cov_2'=>'negative','paho_flu' => '105926','status' => 'Alta','observation' => NULL,'patient_id' =>'22']);
        SuspectCase::CREATE(['sample_at'=>'16-03-2020','origin'=>'Hospital ETG','age'=>'24','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'51640','pscr_sars_cov_2'=>'negative','paho_flu' => '105947','status' => 'Alta','observation' => NULL,'patient_id' =>'23']);
        SuspectCase::CREATE(['sample_at'=>'16-03-2020','origin'=>'Hospital ETG','age'=>'38','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'52104','pscr_sars_cov_2'=>'negative','paho_flu' => '105962','status' => 'Alta','observation' => NULL,'patient_id' =>'24']);
        SuspectCase::CREATE(['sample_at'=>'17-03-2020','origin'=>'Hospital ETG','age'=>'25','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'53578','pscr_sars_cov_2'=>'negative','paho_flu' => '105949','status' => 'Alta','observation' => NULL,'patient_id' =>'25']);
        SuspectCase::CREATE(['sample_at'=>'17-03-2020','origin'=>'Hospital ETG','age'=>'24','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'51713','pscr_sars_cov_2'=>'negative','paho_flu' => '105951','status' => 'Alta','observation' => NULL,'patient_id' =>'26']);
        SuspectCase::CREATE(['sample_at'=>'17-03-2020','origin'=>'Hospital ETG','age'=>'33','gender'=>'male','result_ifd'=>'Influenza B','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'51758','pscr_sars_cov_2'=>'negative','paho_flu' => '105953','status' => 'Alta','observation' => NULL,'patient_id' =>'27']);
        SuspectCase::CREATE(['sample_at'=>'17-03-2020','origin'=>'Hospital ETG','age'=>'34','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'51833','pscr_sars_cov_2'=>'negative','paho_flu' => '105956','status' => 'Alta','observation' => NULL,'patient_id' =>'28']);
        SuspectCase::CREATE(['sample_at'=>'17-03-2020','origin'=>'Hospital ETG','age'=>'20','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'53081','pscr_sars_cov_2'=>'negative','paho_flu' => '105944','status' => 'Alta','observation' => NULL,'patient_id' =>'29']);
        SuspectCase::CREATE(['sample_at'=>'17-03-2020','origin'=>'Hospital ETG','age'=>'32','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'52425','pscr_sars_cov_2'=>'negative','paho_flu' => '105963','status' => 'Alta','observation' => NULL,'patient_id' =>'30']);
        SuspectCase::CREATE(['sample_at'=>'17-03-2020','origin'=>'Hospital ETG','age'=>'33','gender'=>'male','result_ifd'=>'VRS','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'52907','pscr_sars_cov_2'=>'negative','paho_flu' => '105965','status' => 'Alta','observation' => 'VRS+/NO SE LOGRA ESTABLECER COMUNICACIÓN CON PACIENTE, NUMEROS TELEFONICOS ENTREGADOS NO RESPONDEN','patient_id' =>'31']);
        SuspectCase::CREATE(['sample_at'=>'17-03-2020','origin'=>'Hospital ETG','age'=>'34','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'52865','pscr_sars_cov_2'=>'negative','paho_flu' => '105964','status' => 'Alta','observation' => NULL,'patient_id' =>'32']);
        SuspectCase::CREATE(['sample_at'=>'18-03-2020','origin'=>'Hospital ETG','age'=>'0.1','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'52714','pscr_sars_cov_2'=>'negative','paho_flu' => '105915','status' => 'Hospitalizado Crítico','observation' => 'SE REINGRESA A EPIVIGILIA, RESIDENTE UPCP REFIERE QUE CUADRO NOSE COMPORTA COMO MICOPLASMA.','patient_id' =>'33']);
        SuspectCase::CREATE(['sample_at'=>'18-03-2020','origin'=>'Hospital ETG','age'=>'45','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'54441','pscr_sars_cov_2'=>'negative','paho_flu' => '105981','status' => 'Alta','observation' => NULL,'patient_id' =>'34']);
        SuspectCase::CREATE(['sample_at'=>'18-03-2020','origin'=>'Hospital ETG','age'=>'49','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'54380','pscr_sars_cov_2'=>'negative','paho_flu' => '105982','status' => 'Alta','observation' => NULL,'patient_id' =>'35']);
        SuspectCase::CREATE(['sample_at'=>'19-03-2020','origin'=>'Hospital ETG','age'=>'63','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'54575','pscr_sars_cov_2'=>'negative','paho_flu' => '105983','status' => 'Hospitalizado Básico','observation' => 'IRAG','patient_id' =>'36']);
        SuspectCase::CREATE(['sample_at'=>'19-03-2020','origin'=>'Hospital ETG','age'=>'54','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'54369','pscr_sars_cov_2'=>'negative','paho_flu' => '105984','status' => 'Alta','observation' => NULL,'patient_id' =>'37']);
        SuspectCase::CREATE(['sample_at'=>'19-03-2020','origin'=>'Hospital ETG','age'=>'28','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'53764','pscr_sars_cov_2'=>'negative','paho_flu' => '105985','status' => 'Alta','observation' => NULL,'patient_id' =>'38']);
        SuspectCase::CREATE(['sample_at'=>'19-03-2020','origin'=>'Hospital ETG','age'=>'22','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'54329','pscr_sars_cov_2'=>'negative','paho_flu' => '105987','status' => 'Alta','observation' => NULL,'patient_id' =>'39']);
        SuspectCase::CREATE(['sample_at'=>'19-03-2020','origin'=>'Hospital ETG','age'=>'27','gender'=>'male','result_ifd'=>'Influenza A','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'54289','pscr_sars_cov_2'=>'negative','paho_flu' => '105988','status' => 'Alta','observation' => NULL,'patient_id' =>'40']);
        SuspectCase::CREATE(['sample_at'=>'19-03-2020','origin'=>'Hospital ETG','age'=>'2','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'54628','pscr_sars_cov_2'=>'negative','paho_flu' => '105996','status' => 'Alta','observation' => NULL,'patient_id' =>'41']);
        SuspectCase::CREATE(['sample_at'=>'19-03-2020','origin'=>'Hospital ETG','age'=>'3','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'54739','pscr_sars_cov_2'=>'negative','paho_flu' => '105997','status' => 'Alta','observation' => NULL,'patient_id' =>'42']);
        SuspectCase::CREATE(['sample_at'=>'19-03-2020','origin'=>'Hospital ETG','age'=>'37','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'54780','pscr_sars_cov_2'=>'negative','paho_flu' => '105998','status' => 'Alta','observation' => NULL,'patient_id' =>'43']);
        SuspectCase::CREATE(['sample_at'=>'19-03-2020','origin'=>'Hospital ETG','age'=>'41','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'55011','pscr_sars_cov_2'=> 'pending','paho_flu' => '105999','status' => 'Alta','observation' => 'ALTA (SIN EMBARGO PACIENTE DE PASO EN CHILE  Y LA AMIGA DONDE SE ESTABA ALOJANDO NO LA RECIBIO)','patient_id' =>'44']);
        SuspectCase::CREATE(['sample_at'=>'19-03-2020','origin'=>'Hospital ETG','age'=>'35','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'55402','pscr_sars_cov_2'=> 'pending','paho_flu' => '196000','status' => 'Alta','observation' => NULL,'patient_id' =>'45']);
        SuspectCase::CREATE(['sample_at'=>'20-03-2020','origin'=>'Hospital ETG','age'=>'51','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'55410','pscr_sars_cov_2'=>'negative','paho_flu' => '106001','status' => 'Alta','observation' => NULL,'patient_id' =>'46']);
        SuspectCase::CREATE(['sample_at'=>'20-03-2020','origin'=>'Hospital ETG','age'=>'47','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'55418','pscr_sars_cov_2'=> 'positive','paho_flu' => '106002','status' => 'Alta','observation' => NULL,'patient_id' =>'47']);
        SuspectCase::CREATE(['sample_at'=>'20-03-2020','origin'=>'Hospital ETG','age'=>'22','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'55432','pscr_sars_cov_2'=> 'pending','paho_flu' => '106003','status' => 'Alta','observation' => 'ALTA (sin rut identificacion local)','patient_id' =>'48']);
        SuspectCase::CREATE(['sample_at'=>'20-03-2020','origin'=>'Hospital ETG','age'=>'17','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'55446','pscr_sars_cov_2'=> 'pending','paho_flu' => '106004','status' => 'Alta','observation' => NULL,'patient_id' =>'49']);
        SuspectCase::CREATE(['sample_at'=>'20-03-2020','origin'=>'Hospital ETG','age'=>'20','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'55787','pscr_sars_cov_2'=> 'pending','paho_flu' => '106009','status' => 'Alta','observation' => NULL,'patient_id' =>'50']);
        SuspectCase::CREATE(['sample_at'=>'20-03-2020','origin'=>'Hospital ETG','age'=>'31','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'55570','pscr_sars_cov_2'=> 'pending','paho_flu' => '106006','status' => 'Alta','observation' => NULL,'patient_id' =>'51']);
        SuspectCase::CREATE(['sample_at'=>'20-03-2020','origin'=>'Hospital ETG','age'=>'7','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'55605','pscr_sars_cov_2'=> 'pending','paho_flu' => '106008','status' => 'Hospitalizado Básico','observation' => NULL,'patient_id' =>'52']);
        SuspectCase::CREATE(['sample_at'=>'20-03-2020','origin'=>'Hospital ETG','age'=>'27','gender'=>'male','result_ifd'=>'Influenza A ','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'55862','pscr_sars_cov_2'=> 'pending','paho_flu' => '106010','status' => 'Alta','observation' => NULL,'patient_id' =>'53']);
        SuspectCase::CREATE(['sample_at'=>'20-03-2020','origin'=>'Hospital ETG','age'=>'39','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'56090','pscr_sars_cov_2'=> 'pending','paho_flu' => '106018','status' => 'Alta','observation' => NULL,'patient_id' =>'54']);
        SuspectCase::CREATE(['sample_at'=>'20-03-2020','origin'=>'Hospital ETG','age'=>'33','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'56221','pscr_sars_cov_2'=> 'pending','paho_flu' => '106020','status' => 'Alta','observation' => NULL,'patient_id' =>'55']);
        SuspectCase::CREATE(['sample_at'=>'20-03-2020','origin'=>'Hospital ETG','age'=>'37','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'56239','pscr_sars_cov_2'=> 'pending','paho_flu' => '106021','status' => 'Alta','observation' => NULL,'patient_id' =>'56']);
        SuspectCase::CREATE(['sample_at'=>'20-03-2020','origin'=>'Hospital ETG','age'=>'70','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'56268','pscr_sars_cov_2'=> 'pending','paho_flu' => '106022','status' => 'Alta','observation' => NULL,'patient_id' =>'57']);
        SuspectCase::CREATE(['sample_at'=>'20-03-2020','origin'=>'Hospital ETG','age'=>'83','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'56178','pscr_sars_cov_2'=> 'pending','paho_flu' => '106023','status' => 'Alta','observation' => NULL,'patient_id' =>'58']);
        SuspectCase::CREATE(['sample_at'=>'20-03-2020','origin'=>'Hospital ETG','age'=>'21','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'56295','pscr_sars_cov_2'=> 'pending','paho_flu' => '106024','status' => 'Alta','observation' => NULL,'patient_id' =>'59']);
        SuspectCase::CREATE(['sample_at'=>'20-03-2020','origin'=>'CESFAM Guzmán','age'=>'27','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=> NULL,'pscr_sars_cov_2'=> 'pending','paho_flu' => NULL,'status' => 'Ambulatorio','observation' => 'APS','patient_id' =>'60']);
        SuspectCase::CREATE(['sample_at'=>'20-03-2020','origin'=>'CESFAM Guzmán','age'=>'56','gender'=>'male','result_ifd'=>'Parainfluenza 1','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=> NULL,'pscr_sars_cov_2'=> 'pending','paho_flu' => NULL,'status' => 'Ambulatorio','observation' => 'APS','patient_id' =>'61']);
        SuspectCase::CREATE(['sample_at'=>'20-03-2020','origin'=>'CESFAM Guzmán','age'=>'27','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=> NULL,'pscr_sars_cov_2'=> 'pending','paho_flu' => NULL,'status' => 'Ambulatorio','observation' => 'APS','patient_id' =>'62']);
        SuspectCase::CREATE(['sample_at'=>'20-03-2020','origin'=>'Hospital ETG','age'=>'64','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'56329','pscr_sars_cov_2'=> 'pending','paho_flu' => '106025','status' => 'Alta','observation' => NULL,'patient_id' =>'63']);
        SuspectCase::CREATE(['sample_at'=>'20-03-2020','origin'=>'Hospital ETG','age'=>'63','gender'=>'male','result_ifd'=> NULL,'subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'55948','pscr_sars_cov_2'=> 'pending','paho_flu' => NULL,'status' => 'Hospitalizado Básico','observation' => '2da Muestra','patient_id' =>'64']);
        SuspectCase::CREATE(['sample_at'=>'20-03-2020','origin'=>'Hospital ETG','age'=>'40','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'57294','pscr_sars_cov_2'=> 'pending','paho_flu' => '106026','status' => 'Alta','observation' => NULL,'patient_id' =>'65']);
        SuspectCase::CREATE(['sample_at'=>'20-03-2020','origin'=>'Hospital ETG','age'=>'26','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'57150','pscr_sars_cov_2'=> 'pending','paho_flu' => '106027','status' => 'Alta','observation' => NULL,'patient_id' =>'66']);
        SuspectCase::CREATE(['sample_at'=>'20-03-2020','origin'=>'Clínica Tarapacá','age'=>'31','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'55809','pscr_sars_cov_2'=> 'positive','paho_flu' => '106028','status' => 'Alta','observation' => NULL,'patient_id' =>'67']);
        SuspectCase::CREATE(['sample_at'=>'21-03-2020','origin'=>'Clínica Iquique','age'=>'32','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'55953','pscr_sars_cov_2'=> 'pending','paho_flu' => '106029','status' => 'Alta','observation' => NULL,'patient_id' =>'68']);
        SuspectCase::CREATE(['sample_at'=>'21-03-2020','origin'=>'Hospital ETG','age'=>'31','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'56768','pscr_sars_cov_2'=> 'pending','paho_flu' => '106030','status' => 'Alta','observation' => NULL,'patient_id' =>'69']);
        SuspectCase::CREATE(['sample_at'=>'21-03-2020','origin'=>'Hospital ETG','age'=>'46','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'56795','pscr_sars_cov_2'=> 'pending','paho_flu' => '106019','status' => 'Alta','observation' => NULL,'patient_id' =>'70']);
        SuspectCase::CREATE(['sample_at'=>'21-03-2020','origin'=>'Hospital ETG','age'=>'67','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'56952','pscr_sars_cov_2'=> 'pending','paho_flu' => '106031','status' => 'Alta','observation' => NULL,'patient_id' =>'71']);
        SuspectCase::CREATE(['sample_at'=>'21-03-2020','origin'=>'Hector Reyno','age'=>'1','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'56789','pscr_sars_cov_2'=> 'pending','paho_flu' => '106032','status' => 'Alta','observation' => NULL,'patient_id' =>'72']);
        SuspectCase::CREATE(['sample_at'=>'21-03-2020','origin'=>'Hector Reyno','age'=>'35','gender'=>'female','result_ifd'=>'Influenza A','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=> NULL,'pscr_sars_cov_2'=> 'pending','paho_flu' => NULL,'status' => 'Ambulatorio','observation' => 'APS','patient_id' =>'73']);
        SuspectCase::CREATE(['sample_at'=>'21-03-2020','origin'=>'Hospital ETG','age'=>'57','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'57512','pscr_sars_cov_2'=> 'pending','paho_flu' => '106034','status' => 'Alta','observation' => NULL,'patient_id' =>'74']);
        SuspectCase::CREATE(['sample_at'=>'21-03-2020','origin'=>'Hospital ETG','age'=>'34','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'57501','pscr_sars_cov_2'=> 'pending','paho_flu' => '106033','status' => 'Alta','observation' => NULL,'patient_id' =>'75']);
        SuspectCase::CREATE(['sample_at'=>'21-03-2020','origin'=>'Hector Reyno','age'=>'10','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=> NULL,'pscr_sars_cov_2'=> 'pending','paho_flu' => NULL,'status' => 'Ambulatorio','observation' => 'APS','patient_id' =>'76']);
        SuspectCase::CREATE(['sample_at'=>'21-03-2020','origin'=>'Hospital ETG','age'=>'91','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'58194','pscr_sars_cov_2'=> 'pending','paho_flu' => NULL,'status' => 'Alta','observation' => NULL,'patient_id' =>'77']);
        SuspectCase::CREATE(['sample_at'=>'21-03-2020','origin'=>'Hospital ETG','age'=>'33','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'58200','pscr_sars_cov_2'=> 'pending','paho_flu' => NULL,'status' => 'Alta','observation' => NULL,'patient_id' =>'78']);
        SuspectCase::CREATE(['sample_at'=>'21-03-2020','origin'=>'Hector Reyno','age'=>'30','gender'=>'male','result_ifd'=>'Influenza A','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=> NULL,'pscr_sars_cov_2'=> 'pending','paho_flu' => NULL,'status' => 'Ambulatorio','observation' => 'APS','patient_id' =>'79']);
        SuspectCase::CREATE(['sample_at'=>'21-03-2020','origin'=>'Hospital ETG','age'=>'79','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=>'58205','pscr_sars_cov_2'=> 'pending','paho_flu' => NULL,'status' => 'Alta','observation' => NULL,'patient_id' =>'80']);
        SuspectCase::CREATE(['sample_at'=>'21-03-2020','origin'=>'Hector Reyno','age'=>'13','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'12','epivigila'=> NULL,'pscr_sars_cov_2'=> 'pending','paho_flu' => NULL,'status' => 'Ambulatorio','observation' => 'APS','patient_id' =>'81']);
        SuspectCase::CREATE(['sample_at'=>'22-03-2020','origin'=>'Hospital ETG','age'=>'40','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'13','epivigila'=>'58221','pscr_sars_cov_2'=> 'pending','paho_flu' => NULL,'status' => 'Alta','observation' => NULL,'patient_id' =>'82']);
        SuspectCase::CREATE(['sample_at'=>'22-03-2020','origin'=>'Hospital ETG','age'=>'28','gender'=>'female','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'13','epivigila'=> NULL,'pscr_sars_cov_2'=> 'pending','paho_flu' => NULL,'status' => 'Alta','observation' => NULL,'patient_id' =>'83']);
        SuspectCase::CREATE(['sample_at'=>'22-03-2020','origin'=>'Hospital ETG','age'=>'49','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'13','epivigila'=> NULL,'pscr_sars_cov_2'=> 'pending','paho_flu' => NULL,'status' => 'Hospitalizado Básico','observation' => NULL,'patient_id' =>'84']);
        SuspectCase::CREATE(['sample_at'=>'22-03-2020','origin'=>'Hospital ETG','age'=>'57','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'13','epivigila'=> NULL,'pscr_sars_cov_2'=> 'pending','paho_flu' => NULL,'status' => 'Hospitalizado Básico','observation' => NULL,'patient_id' =>'85']);
        SuspectCase::CREATE(['sample_at'=>'22-03-2020','origin'=>'Hector Reyno','age'=>'2','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'13','epivigila'=> NULL,'pscr_sars_cov_2'=> 'pending','paho_flu' => NULL,'status' => 'Ambulatorio','observation' => 'APS','patient_id' =>'86']);
        SuspectCase::CREATE(['sample_at'=>'22-03-2020','origin'=>'Hospital ETG','age'=>'27','gender'=>'male','result_ifd'=>'Influenza A','subtype' => NULL,'epidemiological_week'=>'13','epivigila'=> NULL,'pscr_sars_cov_2'=> 'pending','paho_flu' => NULL,'status' => 'Alta','observation' => NULL,'patient_id' =>'87']);
        SuspectCase::CREATE(['sample_at'=>'22-03-2020','origin'=>'Hospital ETG','age'=>'38','gender'=>'male','result_ifd'=>'Negativo','subtype' => NULL,'epidemiological_week'=>'13','epivigila'=> NULL,'pscr_sars_cov_2'=> 'pending','paho_flu' => NULL,'status' => 'Alta','observation' => NULL,'patient_id' =>'88']);
        SuspectCase::CREATE(['sample_at'=>'22-03-2020','origin'=>'Hospital ETG','age'=>'91','gender'=>'female','result_ifd'=> NULL,'subtype' => NULL,'epidemiological_week'=>'13','epivigila'=> NULL,'pscr_sars_cov_2'=> 'pending','paho_flu' => NULL,'status' => 'Hospitalizado Básico','observation' => NULL,'patient_id' =>'89']);
        SuspectCase::CREATE(['sample_at'=>'22-03-2020','origin'=>'Hospital ETG','age'=>'29','gender'=>'male','result_ifd'=> NULL,'subtype' => NULL,'epidemiological_week'=>'13','epivigila'=> NULL,'pscr_sars_cov_2'=> 'pending','paho_flu' => NULL,'status' => 'Hospitalizado Básico','observation' => NULL,'patient_id' =>'90']);

    }
}
