FROM php:fpm

RUN apt-get update &&  \
	apt-get install -y \
		libsqlite3-dev \
		libzip-dev \
		zlib1g-dev \
		libpng-dev \
		libonig-dev \
		nginx \
		nano \
		supervisor && \
    rm -rf /var/lib/apt/lists/* && \
	curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
	docker-php-ext-install -j$(nproc) pdo && \
	docker-php-ext-install -j$(nproc) pdo_mysql && \
	docker-php-ext-install -j$(nproc) pdo_sqlite && \
	docker-php-ext-install -j$(nproc) zip && \
	docker-php-ext-install -j$(nproc) mbstring && \
	docker-php-ext-install -j$(nproc) gd

COPY . /var/www/html
WORKDIR /var/www/html

RUN composer install
RUN rm /etc/nginx/sites-enabled/default

COPY ./deploy/deploy.conf /etc/nginx/conf.d/default.conf

RUN mv /usr/local/etc/php-fpm.d/www.conf /usr/local/etc/php-fpm.d/www.conf.backup
COPY ./deploy/www.conf /usr/local/etc/php-fpm.d/www.conf

RUN usermod -a -G www-data root
RUN chgrp -R www-data storage

RUN chown -R www-data:www-data ./storage
RUN chmod -R 0777 ./storage

RUN chmod +x ./deploy/run

CMD ["./deploy/run"]

EXPOSE 80
